config/routes.rb
Rails.application.routes.draw do
  resources :complaints
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/complaint_form' =>'complaints#complaint_form', :as => :complaint_form
  get '/completed' => 'complaints#complaint_completed', :as => :completed
  get '/confirmation' =>'complaints#confirmation', :as => :confirmation
  get '/user_panel' => 'user_panel#index', :as => :user_panel
 

  
  root "landing_page#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
    def self.show_all
        return Complaint.all
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  # GET /complaints
  # GET /complaints.json
  def index
    @complaints = Complaint.all
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = Complaint.new
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @complaint = Complaint.new(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: 'Complaint was successfully created.' }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /complaints/1
  # PATCH/PUT /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: 'Complaint was successfully updated.' }
        format.json { render :show, status: :ok, location: @complaint }
      else
        format.html { render :edit }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: 'Complaint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def complaint_params
      params.require(:complaint).permit(:department, :city, :date_event, :email, :description, :file, :clasification, :organization, :latitude, :longitude)
    end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
end

app/controllers/user_panel_controller.rb
class UserPanelController < ApplicationController

    def index
        @complaints = Complaint.show_all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/user_panel_helper.rb
module UserPanelHelper
end

app/views/complaint/index.html.erb
<%= render "layouts/header" %>

<script>
  $(document).ready(function (){
    $('.modal').modal();
  });
</script>

<div class="container">
  <div class="row">
    <span class="col s8 offset-s2">
      <h1 class="center">¡Tu denuncia ha sido registrada!</h1>
    </span>
  </div>
  <form class="col s10 offset-s1">
    <div class="row">
      <div class="input-field col s4">
          <input id="complaint-departamento" type="text" value="Departamento1" class="validate" disabled/>
        <label for="complaint-departamento" class="active">Departamento:</label>
      </div>
      <div class="input-field col s4">
        <input id="complaint-municipio" type="text" value="Municipio1" class="validate" disabled/>
        <label for="complaint-municipio" class="active">Municipio:</label>
      </div>
      <div class="input-field col s4">
        <input id="complaint-social-group" type="text" value="GrupoSocial1" class="validate" disabled/>
        <label for="complaint-social-group" class="active">Grupo social:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6">
        <input id="complaint-fecha" type="date" value="2019-07-19" class="datepicker" disabled/>
        <label for="complaint-fecha">Fecha del suceso:</label>
      </div>
      <div class="input-field col s6">
        <input id="complaint-email" type="email" value="email@gmail.com" class="validate" disabled>
        <label for="complaint-email" class="active">Correo de contacto:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <textarea id="complaint-textarea1" value="" class="materialize-textarea" disabled>Default comment</textarea>
        <label for="complaint-textarea1" class="active">Cuentanos como sucedieron los hechos:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <input id="complaint-archivo" type="text" value="Archivo1.jpg" class="validate" disabled>
        <label for="complaint-archivo" class="active">Archivos</label>
      </div>
    </div>
    <br>
    <a href="#modal1" class="waves-effect waves-light btn modal-trigger">Finalizar</a>
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4 class="center">Gracias por compartirnos tu caso</h4>
        <p class="center">Espera el aviso de alguna de las entidades que seleccionaste</p>
      </div>
      <div class="modal-footer">
        <a href="<%= root_path %>" class="modal-close waves-effect waves-green btn-flat">Aceptar</a>
      </div>
    </div>
  </form>
</div>

app/views/complaints/_form.html.erb
<%= javascript_include_tag    'application.js' %>

<%= form_with(model: complaint, local: true) do |form| %>

<div class="col s10 offset-s1" style="margin-bottom: 100px;">
  <div class="row">
    <div class="col s7 social-group" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
      <div class="grup input-field col s12">
        
        <%= form.select(:clasification, options_for_select([["Lider social","Lider social"],["Lider comunal","Lider comunal"],["Lider ambiental","Lider ambiental"], ["Lider de JAC","Lider de JAC"]]) ) %>
        <label>Selecciona el grupo social al cual perteneces:</label>
      </div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="org input-field col s12">
      
        <%= form.select(:organization, options_for_select([["Somos Defensores","Somos Defensores"],["FLIP","FLIP"],["CINEP","CINEP"],["No estoy seguro","No estoy seguro"]]) ) %>
        <label>Selecciona la organización con la cual te gustaría compartir tu caso:</label>
      </div>

      <%= form.text_field :department, class: "validate", style:"display:none"%>
      <%= form.text_field :city, class: "validate", style:"display:none"%>
      <%= form.text_field :date_event, class: "datepicker", style:"display:none"%>
      <%= form.text_field :email, class: "validate", style:"display:none"%>
      <%= form.text_field :description, class: "validate", style:"display:none"%>
      <%= form.text_field :file, class: "validate", style:"display:none"%>

      <br>

      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>

      <!-- <a id="social_group_continue" onclick="verify(event); location.reload();" href="<%= completed_path %>"
        class="waves-effect waves-light btn right">Continuar</a> -->
        <%= form.submit "Continuar", class: "waves-effect waves-light btn right", style: "color: white;"%>
      <a onclick="" href="<%= complaint_form_path %>" class="waves-effect waves-light btn left">Volver</a>
    </div>
  </div>
  </div>
</div>




<% end %>

app/views/complaints/complaint_form.html.erb
<%= render "layouts/header" %>

<div class="container">
  <div class="row">
    <span class="col s8 offset-s2">
      <h1 class="user-panel-title center">Formulario de denuncia</h1>
      <p class="center">Si estas de acuerdo con compartir tu información de cuerdo a lo expresado anteriormente,
        te solicitamos llenar el siguiente formulario.
      </p>
    </span>
  </div>
  <div class="row">
    <form class="col s10 offset-s1">
      <div class="row">
        <div class="dep input-field col s6">
          <select id="departamento">
            <option value="" disabled selected></option>
            <option value="Amazonas">Amazonas</option>
            <option value="Bolivar">Bolivar</option>
            <option value="Casanare">Casanare</option>
            <option value="Atlantico">Atlantico</option>
            <option value="Risaralda">Risaralda</option>
            <option value="Cundinamarca">Cundinamarca</option>
            <option value="Valle del Cauca">Valle del Cauca</option>
            <option value="Cauca">Cauca</option>
            <option value="Antioquia">Antioquia</option>
          </select>
          <label>Departamento:</label>
        </div>
        <div class="mun input-field col s6">
          <select id="municipio">
            <option value="" disabled selected></option>
            <option value="Barranquilla">Barranquilla</option>
            <option value="Bogota">Bogota</option>
            <option value="Cartagena">Cartagena</option>
            <option value="Medellin">Medellin</option>
            <option value="La Ceja">La Ceja</option>
            <option value="Cali">Cali</option>
            <option value="Chia">Chia</option>
          </select>
          <label for="municipio">Municipio:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input id="fecha" type="date" class="datepicker" />
          <label for="fecha" class="active">Fecha del suceso:</label>
        </div>
        <div class="input-field col s6">
          <input id="email" type="email" class="validate" placeholder=" ">
          <label for="email" class="active">Correo de contacto:</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" class="materialize-textarea" placeholder=" "></textarea>
          <label for="textarea1" class="active">Cuentanos como sucedieron los hechos:</label>
        </div>
      </div>
      <div class="row">
        <div class="file-field input-field col s12">
          <div class="btn">
            <span>Cargar Archivo</span>
            <input id="archivo" type="file" multiple>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text" placeholder="Puedes subir uno o más archivos"">
          </div>
        </div>
      </div>
      <br>
      <a id="comp_form_continue" onclick="verify(event);" href="<%= new_complaint_path %>" class="waves-effect waves-light btn right" onclick="location.reload()">Continuar</a>
      <a onclick="comeBack(event);" href="<%= confirmation_path %>" class="waves-effect waves-light btn left">Volver</a>
    </form>
  </div>
</div>

app/views/complaints/confirmation.html.erb
<%= render "layouts/header" %>

<div class="container ">
  <div class="row">
  </div>
  <div class="row">
    <div class="col s12 ">
      <div class="card">
        <div class="card-image">
          <img src="<%= asset_path('lideres.jpeg') %>" height="400px">
          <span class="card-title confirmation-atencion">ATENCIÓN</span>
        </div>
        <div class="card-content">
          <p class="confirmation-paragraph">Si te reconoces como defensor de derechos humanos o eres lider social, comunal o 
              indigena y has sido víctima de agresiones que pongan en peligro tu vida, tu 
              integridad o tu trabajo, te proponemos compartir dicha información con nosotros; 
              de forma que podamos hacerla llegar a las organizaciones comprometidas con la 
              prevención de agresiones y protección de la vida de las personas que corren 
              riesgo por su labor como defensores de derechos humanos. 
              <br><br>
              El ingreso de esta información a este registro es absolutamente voluntario y tiene 
              fines netamente estadísticos, ya que el Programa no asume el seguimiento, tramite 
              o transferencia de ninguna denuncia consignada en esta web a autoridades.
              <br><br>
              A continuación encontrarás un formulario donde podrás adjuntar la información 
              relacionada con tu caso. Puedes incluir archivos con los comunicados o denuncias
              públicas sobre tu caso.</p>
        </div>
        <div class="card-action">
          <a href="<%= root_path %>">Volver</a>
          <a href="<%= complaint_form_path %>" onclick="location.reload();" >Continuar</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/complaints/edit.html.erb
<h1>Editing Complaint</h1>

<%= render 'form', complaint: @complaint %>

<%= link_to 'Show', @complaint %> |
<%= link_to 'Back', complaints_path %>

app/views/complaints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>City</th>
      <th>Date event</th>
      <th>Email</th>
      <th>Description</th>
      <th>File</th>
      <th>Clasification</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.department %></td>
        <td><%= complaint.city %></td>
        <td><%= complaint.date_event %></td>
        <td><%= complaint.email %></td>
        <td><%= complaint.description %></td>
        <td><%= complaint.file %></td>
        <td><%= complaint.clasification %></td>
        <td><%= complaint.organization %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/index_aux.html.erb
<p id="notice"><%= notice %></p>

<h1>Complaints</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>City</th>
      <th>Date event</th>
      <th>Email</th>
      <th>Description</th>
      <th>File</th>
      <th>Clasification</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.department %></td>
        <td><%= complaint.city %></td>
        <td><%= complaint.date_event %></td>
        <td><%= complaint.email %></td>
        <td><%= complaint.description %></td>
        <td><%= complaint.file %></td>
        <td><%= complaint.clasification %></td>
        <td><%= complaint.organization %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_complaint_path %>

app/views/complaints/new.html.erb
<%= render "layouts/header" %>
<div class="container">
    <%= render 'form', complaint: @complaint %>
</div>

app/views/complaints/show.html.erb
<%= render "layouts/header" %>

<script>
  $(document).ready(function (){
    $('.modal').modal();
  });
</script>

<div class="container">
  <div class="row">
    <span class="col s8 offset-s2">
      <h1 class="center complete-title">¡Tu denuncia ha sido registrada!</h1>
    </span>
  </div>
  
    <form class="col s10 offset-s1" style="margin-bottom: 100px;">
    <div class="row">
      <div class="input-field col s4">
          <input id="complaint_department_" type="text" value="<%= @complaint.department %>" class="validate" disabled/> 
          <label for="complaint_department_" class="active">Departamento:</label>
      </div>
      <div class="input-field col s4">
        <input id="complaint_city_" type="text" value="<%= @complaint.city %>" class="validate" disabled/>
        <label for="complaint_city_" class="active">Municipio:</label>
      </div>
      <div class="input-field col s4">
        <input id="complaint_clasification_" type="text" value="<%= @complaint.clasification %>" class="validate" disabled/>
        <label for="complaint_clasification_" class="active">Grupo social:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6">
        <input id="complaint_date_event_" type="date" value="<%= @complaint.date_event.strftime('%F') %>" disabled/>
        <label for="complaint_date_event_">Fecha del suceso:</label>
      </div>
      <div class="input-field col s6">
        <input id="complaint_email_" type="email" value="<%= @complaint.email %>" class="validate" disabled>
        <label for="complaint_email_" class="active">Correo de contacto:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <textarea id="complaint_description_" value="" class="materialize-textarea" style="overflow-y: scroll; height: 200px;" disabled><%= @complaint.description %></textarea>
        <label for="complaint_description_" class="active">Cuentanos como sucedieron los hechos:</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <input id="complaint_file_" type="text" value="<%= @complaint.file %>" class="validate" disabled>
        <label for="complaint_file_" class="active">Archivos</label>
      </div>
    </div>
    <br>
    <a href="#modal1" class="waves-effect waves-light btn modal-trigger">Finalizar</a>
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4 class="center">Gracias por compartirnos tu caso</h4>
        <p class="center">Espera el aviso de alguna de las entidades que seleccionaste</p>
      </div>
      <div class="modal-footer">
        <a href="<%= root_path %>" class="modal-close waves-effect waves-green btn-flat">Aceptar</a>
      </div>
    </div>
  </form>
  
  
  
    
 


</div>

app/views/confirmation/index.html.erb
<%= render "layouts/header" %>

<div class="container ">
  <div class="row">
  </div>
  <div class="row">
    <div class="col s12 ">
      <div class="card">
        <div class="card-image">
          <img src="<%= asset_path('mapa.png') %>" width="300px" height="300px">
          <span class="card-title confirmation-atencion">ATENCIÓN</span>
        </div>
        <div class="card-content">
          <p class="confirmation-paragraph">Si te reconoces como defensor de derechos humanos o eres lider social, comunal o 
              indigena y has sido víctima de agresiones que pongan en peligro tu vida, tu 
              integridad o tu trabajo, te proponemos compartir dicha información con nosotros; 
              de forma que podamos hacerla llegar a las organizaciones comprometidas con la 
              prevención de agresiones y protección de la vida de las personas que corren 
              riesgo por su labor como defensores de derechos humanos. 
              <br><br>
              El ingreso de esta información a este registro es absolutamente voluntario y tiene 
              fines netamente estadísticos, ya que el Programa no asume el seguimiento, tramite 
              o transferencia de ninguna denuncia consignada en esta web a autoridades.
              <br><br>
              A continuación encontrarás un formulario donde podrás adjuntar la información 
              relacionada con tu caso. Puedes incluir archivos con los comunicados o denuncias
              públicas sobre tu caso.</p>
        </div>
        <div class="card-action">
          <a href="<%= root_path %>">Volver</a>
          <a href="<%= user_panel_path %>">Continuar</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/landing_page/index.html.erb
<div class="container">
  <br><br>
  <h1 class="main-title header center" style="color: #022840 ">CAECUS</h1>
  <div class="col s12 center">

    <p class="light"></p>CAECUS es una aplicación que permite denunciar amenazas a la vida de líderes sociales, defensores de DDHH y en general toda persona que sea perseguida a causa del conflicto armado en Colombia , también pretende ser una herramienta de visualización
    de la problemática con el objetivo de concientizar a la sociedad sobre todos los casos que están sucediendo actualmente.</p>
    <br>
    <h4>¿Qué deseas hacer con CAECUS?</h4>
  </div>

  <br><br>

  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <a href="<%= confirmation_path %>" class="red-button landing_button  waves-effect waves-light btn-large">Denunciar</a>

          <p class="light">Ingresa aquí si necesitas denunciar alguna agresión o amenaza debido a tu labor social o política</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <a href="<%= user_panel_path %>" class="landing_button waves-effect waves-light btn-large">Consultar</a>

          <p class="light">Conoce los datos más recientes sobre asesinatos y amenazas a líderes sociales, comunales e indígenas y a defensores de Derechos Humanos en Colombia</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <a class="landing_button waves-effect waves-light btn-large">Ingresar al sistema</a>

          <p class="light">Si eres una organización defensora de DDHH ingresa o regístrate para acceder a más información.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav role="navigation">
    <div class="nav-wrapper container">
        <%= link_to  root_path do %>
            <img src="<%= asset_path('logo.png') %>" class="mylogo">
            <span>
                <h3 class="header-title">CAECUS</h3>
            </span>
        <% end %>
    </div>
</nav>

app/views/layouts/_load-assets.html.erb
<script type="text/javascript">
    var img_marker_complaint = "<%= asset_path('warning.png') %>"
</script>

app/views/layouts/_map-actions.html.erb
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyXJ70FdiES-rcUtNJEu8HCjr2q7M6bF4&callback=initMap&libraries=visualization">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= csp_meta_tag %>
   
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="<%= asset_path('logo2.png') %>" />

    <title>CAECUS</title>
    
    <%= stylesheet_link_tag    'application' %>
    <%= stylesheet_link_tag    'fonts' %>
    <%= stylesheet_link_tag    'complaint_form' %>
    <%= stylesheet_link_tag    'confirmation' %>
    <%= stylesheet_link_tag    'social_group' %>
    <%= stylesheet_link_tag    'completed' %>
    <%= stylesheet_link_tag    'map_styles' %>

    <%= javascript_include_tag    'application.js' %>
    <%= render "layouts/load-assets" %>
</head>

<body>
    <script>
        $(document).ready(function () {
            $('select').formSelect(); //Sin esto los select no se muestran
        });
    </script>
    <%= yield %>
</body>

</html>

app/views/social_group/index.html.erb
<%= render "layouts/header" %>

<div class="container" >
  <div class="row">
    <form class="col s7 social-group" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
      <div class="grup input-field col s12">
        <select id="grupo" required>
          <option value="" disabled selected></option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
        <label>Selecciona el grupo social al cual perteneces:</label>
      </div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="org input-field col s12">
        <select id="organizacion">
          <option value="" disabled selected></option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
        <label>Selecciona la organización con la cual te gustaría compartir tu caso:</label>
      </div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <a onclick="verify(event);" href="<%= complaint_path %>" class="waves-effect waves-light btn right">Continuar</a>
      <a onclick="" href="<%= user_panel_path %>" class="waves-effect waves-light btn left">Volver</a>
    </form>
  </div>
</div>